name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java-version: [8, 9, 10, 11, 12, 13, 14, 15]

        steps:

        - uses: actions/checkout@v2

        - name: Use Java ${{ matrix.java-version }}
          uses: actions/setup-java@v1
          with:
              java-version: ${{ matrix.java-version }}

        - run: mvn package
